export const NAV_LINKS = [
  { id: 'about', title: 'About' },
  { id: 'work', title: 'Projects' },
  { id: 'skills', title: 'Stack' },
  { id: 'contact', title: 'Contact' },
];

export const PERSONAL_INFO = {
  name: 'Thiago Langone',
  role: 'IT Infrastructure & Automation Engineer',
  email: 'thiagoivan029@gmail.com',
  phone: '+54 9 (11) 2844-1081',
  location: 'Buenos Aires, Argentina',
  github: 'https://github.com/JimmyAlter',
  linkedin: 'https://www.linkedin.com/in/thiago-langone-365825229/',
  bio: 'I look after the infrastructure of a six-company group — 500+ Windows endpoints, six AD domains — and build the tooling that runs it: an in-house RMM, five internal MCP servers, and an agent platform running on self-hosted local models, where every security-critical action runs as deterministic code instead of model output. I also build full-stack apps end to end, from React UIs to Node/Postgres APIs.',
  timezone: 'UTC−3',
  overlap: 'Full day overlap with US Eastern & Central',
  available: true,
};

export const METRICS = [
  { value: '6', label: 'companies supported' },
  { value: '500+', label: 'windows endpoints' },
  { value: '30+', label: 'branch offices' },
  { value: '6', label: 'active directory domains' },
];

export const SKILLS = [
  {
    category: 'Infrastructure & Automation',
    icon: '🖥️',
    items: [
      { name: 'Windows Server', level: 90 },
      { name: 'Active Directory', level: 90 },
      { name: 'PowerShell', level: 85 },
      { name: 'Networking', level: 80 },
      { name: 'Linux', level: 75 },
      { name: 'Google Workspace Admin', level: 75 },
    ],
  },
  {
    category: 'AI Engineering',
    icon: '🤖',
    items: [
      { name: 'Local LLM inference (Ollama)', level: 80 },
      { name: 'Multi-agent orchestration', level: 80 },
      { name: 'MCP server development', level: 80 },
      { name: 'Per-agent tool policies', level: 80 },
      { name: 'Deterministic guardrails', level: 85 },
      { name: 'Gemini API', level: 75 },
    ],
  },
  {
    category: 'Frontend',
    icon: '🎨',
    items: [
      { name: 'React', level: 90 },
      { name: 'JavaScript', level: 85 },
      { name: 'TypeScript', level: 70 },
      { name: 'HTML/CSS', level: 95 },
      { name: 'Tailwind CSS', level: 85 },
      { name: 'Next.js', level: 65 },
    ],
  },
  {
    category: 'Backend',
    icon: '⚙️',
    items: [
      { name: 'Node.js', level: 80 },
      { name: 'Express', level: 75 },
      { name: 'Python', level: 60 },
      { name: 'PostgreSQL', level: 65 },
      { name: 'MongoDB', level: 70 },
      { name: 'REST APIs', level: 85 },
    ],
  },
  {
    category: 'Tools & DevOps',
    icon: '🛠️',
    items: [
      { name: 'Git / GitHub', level: 85 },
      { name: 'Linux', level: 75 },
      { name: 'Docker', level: 55 },
      { name: 'VS Code', level: 90 },
      { name: 'PowerShell', level: 70 },
      { name: 'Vite', level: 80 },
    ],
  },
];

export const projects = [
  {
    title: 'Agent Platform — Local LLM Operations Gateway',
    description: 'An operations gateway running on self-hosted local models (Ollama) — no company data leaves the network. One orchestrator delegates to four isolated specialist agents, each with its own workspace and an explicit tool deny-list. Every security-critical path runs as deterministic code instead of model output.',
    highlights: [
      'Structured queries dropped from 60–150 s of model inference to under 2 s by intercepting intent in code before the model sees the message',
      'Five MCP servers over PostgreSQL and SQL Server — fixed parameterized queries only, password columns excluded by construction, table allowlist enforced in code',
      'Full security review: seven critical findings fixed the same day, plus an append-only audit log for deterministic actions',
    ],
    image: '/projects/agent-platform.svg',
    repoUrl: '',
    liveUrl: '',
    tech: ['Node.js', 'Ollama', 'MCP', 'PostgreSQL', 'SQL Server', 'LDAP', 'Telegram API'],
    featured: true,
    context: 'production',
    gallery: ['/projects/agent-platform.svg'],
  },
  {
    title: 'SystemMonitor (RMM Control)',
    description: 'The in-house RMM I built and operate: a PowerShell agent running as SYSTEM on every workstation, a PostgreSQL back end, a Node/Express API, and a React dashboard. Hardware and software inventory, antivirus and disk alerts, online/offline state, and remote command execution.',
    highlights: [
      'Tracking 500+ Windows endpoints across six companies',
      'Remote command terminal with auditing — message, reboot, gpupdate, PowerShell',
      'Diagnosed 146 workstations that had never reported: the agent was never installed, not the network fault everyone assumed',
    ],
    image: '/projects/systemmonitor-1.png',
    repoUrl: 'https://github.com/JimmyAlter/remote-monitoring-dashboard',
    liveUrl: '',
    tech: ['React', 'Vite', 'Node.js', 'Express', 'PostgreSQL', 'PowerShell', 'Bash', 'TypeScript'],
    featured: true,
    context: 'production',
    gallery: ['/projects/systemmonitor-1.png', '/projects/systemmonitor-2.png'],
  },
  {
    title: 'Mission Control — Agent Fleet Dashboard',
    description: 'A Next.js dashboard that monitors the agent fleet in real time. It reads the gateway roster every 60 seconds and renders each agent on an office floor plan, backed by SQLite with migrations that apply on boot.',
    highlights: [
      'Rebuilt the floor view on a fixed 32 px tile grid with integer-only zoom, fixing the fractional scaling that was blurring the art',
      'Agent routing by domain, with 19 tests covering routing and map integrity',
      'Runs as a standalone production build with its own scheduler — backups, cleanup, heartbeat, and gateway sync',
    ],
    image: '/projects/mission-control.svg',
    repoUrl: '',
    liveUrl: '',
    tech: ['Next.js 16', 'React', 'TailwindCSS', 'SQLite', 'better-sqlite3'],
    featured: false,
    context: 'production',
    gallery: ['/projects/mission-control.svg'],
  },
  {
    title: 'AI Quest RPG — AI Dungeon Master',
    description: 'A desktop RPG where an LLM acts as dungeon master, generating story, encounters, and NPC dialogue live, while a deterministic engine underneath handles combat, HP/XP, and inventory. Built to explore how far an LLM can go as a narrative engine without ever letting it touch the actual game rules.',
    highlights: [
      'LLM-driven narrative and dialogue via the Gemini API, streamed into a Pygame UI',
      'Deterministic combat, stats, and inventory — the model narrates, it never adjudicates rules',
      'Four playable classes with distinct stats and starting kits',
    ],
    image: '/projects/ai-quest-rpg.svg',
    repoUrl: '',
    liveUrl: '',
    tech: ['Python', 'Pygame', 'Gemini API', 'Threading/Queue'],
    featured: false,
    context: 'personal',
    gallery: ['/projects/ai-quest-rpg.svg'],
  },
  {
    title: 'AssetDesk',
    description: 'Enterprise service desk and asset inventory platform with ticket workflows, device health, and team coverage. Designed for IT operations with a clean UI and secure API.',
    highlights: [
      'Ticket workflows with assignment and status tracking',
      'Asset inventory with device details and health',
      'Secure API with JWT authentication',
    ],
    image: '/projects/assetdesk-1.png',
    repoUrl: 'https://github.com/JimmyAlter/AssetDesk',
    liveUrl: '',
    tech: ['React', 'Vite', 'Node.js', 'Express', 'SQLite', 'JWT'],
    featured: false,
    context: 'personal',
    gallery: ['/projects/assetdesk-1.png', '/projects/assetdesk-2.png'],
  },
  {
    title: 'CommerceSuite',
    description: 'Enterprise procurement storefront with secure checkout, catalog filtering, and admin-ready order management. Designed for internal purchasing teams.',
    highlights: [
      'Product catalog search and filtering',
      'Authenticated checkout flow and user accounts',
      'Order tracking designed for admin extension',
    ],
    image: '/projects/commercesuite-1.png',
    repoUrl: 'https://github.com/JimmyAlter/CommerceSuite',
    liveUrl: '',
    tech: ['React', 'Vite', 'Node.js', 'Express', 'SQLite', 'JWT'],
    featured: false,
    context: 'personal',
    gallery: ['/projects/commercesuite-1.png', '/projects/commercesuite-2.png'],
  },
  {
    title: 'NovaSpend',
    description: 'A mobile expense tracker built with Expo/React Native, paired with a Telegram bot so an expense can be logged from a chat message without opening the app. Data syncs through Firebase so the app and the bot always agree.',
    highlights: [
      'Cross-platform app (iOS/Android/web) with Expo Router and native navigation',
      'Telegram bot for logging expenses via chat, backed by the same Firebase data',
      'Local-first UX with async storage and haptic feedback',
    ],
    image: '/projects/novaspend.svg',
    repoUrl: '',
    liveUrl: '',
    tech: ['React Native', 'Expo', 'TypeScript', 'Firebase', 'Node.js', 'Telegram Bot API'],
    featured: false,
    context: 'personal',
    gallery: ['/projects/novaspend.svg'],
  },
];
